[package]
name = "day08"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cark-aoc-helper = { git = "https://github.com/cark/cark-aoc-helper.git" }

[dev-dependencies]
criterion = "0.3"
